// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAM_eIZmeff5-DrDEKRzDlNPFfTCQGj2OY",
      authDomain: "ciav-556f3.firebaseapp.com",
      projectId: "ciav-556f3",
      storageBucket: "ciav-556f3.firebasestorage.app",
      messagingSenderId: "1081740477821",
      appId: "1:1081740477821:web:ceb6d0da3f79dfb953b814",
      measurementId: "G-SYSJ8FZWT6");

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4jmepSzDjLgVLbG9ESxQyF1sSsjTp0Js',
    appId: '1:1081740477821:ios:fa2f9a0d6042c5fd53b814',
    messagingSenderId: '1081740477821',
    projectId: 'ciav-556f3',
    storageBucket: 'ciav-556f3.firebasestorage.app',
    androidClientId: '1081740477821-06svse2roji5vhfam56gjjsav3hnhlge.apps.googleusercontent.com',
    iosClientId: '1081740477821-msm1sd3p16uge5k6cvqs8rn0k4j6nhln.apps.googleusercontent.com',
    iosBundleId: 'com.signal.buch',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkvK3jBfrReauchNmjy1yk4IRZFu6BnQU',
    appId: '1:1081740477821:android:0c01fdcd760589f453b814',
    messagingSenderId: '1081740477821',
    projectId: 'ciav-556f3',
    storageBucket: 'ciav-556f3.firebasestorage.app',
  );

}